name: CI

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Update submodules
      run: git submodule update --init --recursive

    - name: Install X11 libraries
      run: sudo apt-get update && sudo apt-get install -y libx11-dev libxext-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev

    - name: Set up CMake
      uses: lukka/get-cmake@latest

    - name: Configure CMake
      run: cmake -B build -S .

    - name: Build
      run: cmake --build build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts-linux
        path: build

  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Update submodules
      run: git submodule update --init --recursive

    - name: Set up CMake
      uses: lukka/get-cmake@latest

    - name: Install NASM
      run: choco install nasm

    - name: Add NASM to PATH
      run: echo "C:\Program Files\NASM" >> $GITHUB_PATH
      shell: bash

    - name: Configure CMake
      run: cmake -B build -S . -DAOM_TARGET_CPU=generic

    - name: Build
      run: cmake --build build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts-windows
        path: build

  static-analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Update submodules
      run: git submodule update --init --recursive

    - name: Set up SDL
      uses: libsdl-org/setup-sdl@main

    - name: Set up clang-tidy
      run: sudo apt-get update && sudo apt-get install -y clang-tidy

    - name: Configure CMake with clang-tidy
      run: cmake -B build -S . -DENABLE_CLANG_TIDY=ON

    - name: Run clang-tidy and Generate Report
      run: cmake --build build --target run-clang-tidy

    - name: Upload Clang-Tidy Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: clang-tidy-report
        path: build/clang-tidy-fixes.yaml

    - name: Fail on Clang-Tidy Issues
      if: failure()
      run: |
        echo "Clang-Tidy detected issues. Failing the build."
        exit 1
