name: CMake Build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: lukka/get-cmake@latest

    - name: Install SDL2 on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get install libsdl2-dev

    - name: Install SDL2 on macOS
      if: matrix.os == 'macos-latest'
      run: brew install sdl2

    - name: Install SDL2 on Windows
      if: matrix.os == 'windows-latest'
      run: choco install sdl2

    - name: Configure CMake
      run: cmake -B build -S .

    - name: Build
      run: cmake --build build

    - name: Run tests
      run: ctest --output-on-failure

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: build/
