name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up CMake
        uses: lukka/get-cmake@v2.1.0

      - name: Set up SDL2
        run: |
          if [ ${{ matrix.os }} == 'ubuntu-latest' ]; then
            sudo apt-get update
            sudo apt-get install libsdl2-dev
          elif [ ${{ matrix.os }} == 'macos-latest' ]; then
            brew install sdl2
          elif [ ${{ matrix.os }} == 'windows-latest' ]; then
            choco install sdl2
          fi

      - name: Configure CMake
        run: cmake -B build -S .

      - name: Build
        run: cmake --build build

      - name: Run tests
        run: ctest --test-dir build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build
